"""Search Columns."""
COLUMN_SEARCH_ID = "search_id"
COLUMN_COUNT = "count"
COLUMN_STATUS = "status"
COLUMN_TIME = "time"
COLUMN_NSS_GEN_TIME = "nss_gen_time"
COLUMN_SOURCE_TIME = "source_time"
COLUMN_GROUP_ID = "group_id"
COLUMN_WIDGET = "widget"
COLUMN_QUERY = "query"

COLUMN_REQ_COUNT = "req_count"
COLUMN_STATUS_COUNT = "status_count"
COLUMN_DASHBOARD = "dashboard"
