"""Default constatnts ."""

DEFAULT_LIMIT = 200
DEFAULT_TIMEOUT = 60
DEFAULT_MAX_RETRY = 3
DEFAULT_RETRY_INTERVAL = 15
DEFAULT_VERIFY_SSL = True
DEFAULT_PAGE_SIZE = 10

DEFAULT_SCHEDULER_INTERVAL = 3600

DEFAULT_LOWER_LIMIT = 0
DEFAULT_UPPER_LIMIT = 5000

DEFAULT_INDICATOR_TYPE = "all"
DEFAULT_CONFIDENCE_LEVEL = "high"
DEFAULT_TIME = "24h"

DEFAULT_TIMEOUT_USER_PERMISSIONS = 10
DEFAULT_MAX_RETRY_USER_PERMISSIONS = 1
